#!/usr/bin/env bash

args=( "$@" )

if [ ${#args[@]} -lt 2 ]; then
  echo "usage: lines <cmd> <file>"
  exit 0
fi

file=${args[${#args[@]}-1]}
unset 'args[${#args[@]}-1]'

if [[ ! -f "$file" ]]; then
  echo "$file not found"
  exit 1
fi

for arg in "${args[@]}"; do
  cmd="$cmd$arg "
done

while read line; do
  $cmd "$line";
  if [ ! $? -eq 0 ]; then
    exit 1
  fi
done < $file
